name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch (you can modify as needed)
  pull_request:
    branches:
      - main  # Trigger build on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (required for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image for both amd64 and arm64
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/deltaSpark:latest
        platforms: linux/amd64,linux/arm64  # Build for both amd64 and arm64
        cache-from: type=gha  # Cache Docker layers from GitHub Actions for faster builds
        cache-to: type=gha,mode=max  # Cache Docker layers for future builds

    # Optionally, you can add additional steps to verify the image after pushing
    # e.g., run a script to test the image

